name: Build GSR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
        - name: windows-x64
          runner: windows-latest
          shell: cmd
          build_script: .\windows.bat
          rid: win-x64
          msvc_arch: x64
        - name: windows-arm64
          runner: windows-latest
          shell: cmd
          build_script: .\windows.bat
          rid: win-arm64
          msvc_arch: x64_arm64
        - name: macos-universal
          runner: macos-13
          shell: sh
          build_script: ./osx.sh
          rid: osx
        - name: linux-x64
          runner: ubuntu-latest
          container: debian:11
          shell: sh
          build_script: ./linux.sh
          rid: linux-x64
        - name: linux-arm64
          runner: ubuntu-latest
          container: debian:11
          shell: sh
          build_script: ./linux.sh
          rid: linux-arm64
        - name: android
          runner: ubuntu-latest
          container: debian:11
          shell: sh
          build_script: ./android.sh
          rid: android
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.runner }}
    container: ${{ matrix.platform.container }}
    defaults:
      run:
        shell: ${{ matrix.platform.shell }}
    steps:
    - name: Setup MSVC environment
      if: matrix.platform.msvc_arch != ''
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.platform.msvc_arch }}
    - name: Setup base Linux environment
      if: matrix.platform.container != ''
      run: apt-get update && apt-get install -y git
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        path: GSR
        fetch-depth: 0
        submodules: recursive
    - name: Setup Android release keystore
      env:
        ANDROID_RELEASE_KEYSTORE: ${{ secrets.ANDROID_RELEASE_KEYSTORE }}
      run: |
        echo $ANDROID_RELEASE_KEYSTORE | base64 --decode > $HOME/gsr-release-keystore.jks
    - name: Run CI build script
      env:
        TARGET_RID: ${{ matrix.platform.rid }}
        ANDROID_RELEASE_STOREPASS: ${{ secrets.ANDROID_RELEASE_STOREPASS }}
        ANDROID_RELEASE_KEYALIAS: ${{ secrets.ANDROID_RELEASE_KEYALIAS }}
        ANDROID_RELEASE_KEYPASS: ${{ secrets.ANDROID_RELEASE_KEYPASS }}
      run: |
        cd GSR/.ci
        ${{ matrix.platform.build_script }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: GSR-${{ matrix.platform.rid }}
        path: GSR/output/${{ matrix.platform.rid }}/publish/*
        if-no-files-found: error
